//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCPartsStore.WPF.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PCPartsStore.WPF.Resources.Translation", typeof(Translation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddButton {
            get {
                return ResourceManager.GetString("AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddItemsButton {
            get {
                return ResourceManager.GetString("AddItemsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add single.
        /// </summary>
        public static string AddSingleItemButton {
            get {
                return ResourceManager.GetString("AddSingleItemButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot add zero articles.
        /// </summary>
        public static string CannotAddZeroArtcilesError {
            get {
                return ResourceManager.GetString("CannotAddZeroArtcilesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category name*.
        /// </summary>
        public static string CategoryFormNameLabel {
            get {
                return ResourceManager.GetString("CategoryFormNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Categories.
        /// </summary>
        public static string CategoryMenuItem {
            get {
                return ResourceManager.GetString("CategoryMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category not selected.
        /// </summary>
        public static string CategoryNotSelected {
            get {
                return ResourceManager.GetString("CategoryNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to select a category.
        /// </summary>
        public static string CategoryNotSelectedMessage {
            get {
                return ResourceManager.GetString("CategoryNotSelectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string CategoryViewNameHeader {
            get {
                return ResourceManager.GetString("CategoryViewNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category view.
        /// </summary>
        public static string CategoryViewTextBlock {
            get {
                return ResourceManager.GetString("CategoryViewTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string CreateButton {
            get {
                return ResourceManager.GetString("CreateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Dark.
        /// </summary>
        public static string DarkThemeMenuItem {
            get {
                return ResourceManager.GetString("DarkThemeMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to select an account to deactivate..
        /// </summary>
        public static string DeactivateAccountErrorMessage {
            get {
                return ResourceManager.GetString("DeactivateAccountErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate.
        /// </summary>
        public static string DeactivateButton {
            get {
                return ResourceManager.GetString("DeactivateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditButton {
            get {
                return ResourceManager.GetString("EditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _English.
        /// </summary>
        public static string EnglishLanguageMenuItem {
            get {
                return ResourceManager.GetString("EnglishLanguageMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field is empty.
        /// </summary>
        public static string FieldEmpty {
            get {
                return ResourceManager.GetString("FieldEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go To Register.
        /// </summary>
        public static string GoToRegisterButton {
            get {
                return ResourceManager.GetString("GoToRegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Grey.
        /// </summary>
        public static string GreyThemeMenuItem {
            get {
                return ResourceManager.GetString("GreyThemeMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account not active, contact Administrator for help..
        /// </summary>
        public static string InactiveAccount {
            get {
                return ResourceManager.GetString("InactiveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password.
        /// </summary>
        public static string InvalidUsernamePasswordCombo {
            get {
                return ResourceManager.GetString("InvalidUsernamePasswordCombo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item not selected.
        /// </summary>
        public static string ItemNotSelected {
            get {
                return ResourceManager.GetString("ItemNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ItemViewNameHeader {
            get {
                return ResourceManager.GetString("ItemViewNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string ItemViewPriceHeader {
            get {
                return ResourceManager.GetString("ItemViewPriceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string ItemViewQuantityHeader {
            get {
                return ResourceManager.GetString("ItemViewQuantityHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Languages.
        /// </summary>
        public static string LanguagesMenuItem {
            get {
                return ResourceManager.GetString("LanguagesMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Light.
        /// </summary>
        public static string LightThemeMenuItem {
            get {
                return ResourceManager.GetString("LightThemeMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Logout.
        /// </summary>
        public static string LogoutMenuItem {
            get {
                return ResourceManager.GetString("LogoutMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer country*.
        /// </summary>
        public static string ManufacturerFormCountryLabel {
            get {
                return ResourceManager.GetString("ManufacturerFormCountryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer name*.
        /// </summary>
        public static string ManufacturerFormNameLabel {
            get {
                return ResourceManager.GetString("ManufacturerFormNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Manufacturers.
        /// </summary>
        public static string ManufacturerMenuItem {
            get {
                return ResourceManager.GetString("ManufacturerMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer not selected.
        /// </summary>
        public static string ManufacturerNotSelected {
            get {
                return ResourceManager.GetString("ManufacturerNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to select a manufacturer.
        /// </summary>
        public static string ManufacturerNotSelectedMessage {
            get {
                return ResourceManager.GetString("ManufacturerNotSelectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string ManufacturerViewCountryHeader {
            get {
                return ResourceManager.GetString("ManufacturerViewCountryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ManufacturerViewNameHeader {
            get {
                return ResourceManager.GetString("ManufacturerViewNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer View.
        /// </summary>
        public static string ManufacturerViewTextBlock {
            get {
                return ResourceManager.GetString("ManufacturerViewTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No more articles in storage.
        /// </summary>
        public static string NoMoreArticlesLeftError {
            get {
                return ResourceManager.GetString("NoMoreArticlesLeftError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to select a receipt.
        /// </summary>
        public static string NoReceiptErrorMessage {
            get {
                return ResourceManager.GetString("NoReceiptErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password field cannot be blank.
        /// </summary>
        public static string PasswordEmptyErrorMessage {
            get {
                return ResourceManager.GetString("PasswordEmptyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password*.
        /// </summary>
        public static string PasswordTextBlock {
            get {
                return ResourceManager.GetString("PasswordTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Products.
        /// </summary>
        public static string ProductMenuItem {
            get {
                return ResourceManager.GetString("ProductMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to select a product.
        /// </summary>
        public static string ProductNotSelectedMessage {
            get {
                return ResourceManager.GetString("ProductNotSelectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string ProductViewCategoryHeader {
            get {
                return ResourceManager.GetString("ProductViewCategoryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer.
        /// </summary>
        public static string ProductViewManufacturerHeader {
            get {
                return ResourceManager.GetString("ProductViewManufacturerHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturing Year.
        /// </summary>
        public static string ProductViewManufacturingYearHeader {
            get {
                return ResourceManager.GetString("ProductViewManufacturingYearHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ProductViewNameHeader {
            get {
                return ResourceManager.GetString("ProductViewNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string ProductViewPriceHeader {
            get {
                return ResourceManager.GetString("ProductViewPriceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string ProductViewQuantityHeader {
            get {
                return ResourceManager.GetString("ProductViewQuantityHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough articles in storage.
        /// </summary>
        public static string QuantityExceededError {
            get {
                return ResourceManager.GetString("QuantityExceededError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt is empty.
        /// </summary>
        public static string ReceiptEmpty {
            get {
                return ResourceManager.GetString("ReceiptEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt Id.
        /// </summary>
        public static string ReceiptIdHeader {
            get {
                return ResourceManager.GetString("ReceiptIdHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Receipts.
        /// </summary>
        public static string ReceiptMenuItem {
            get {
                return ResourceManager.GetString("ReceiptMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to select a receipt.
        /// </summary>
        public static string ReceiptNotSelected {
            get {
                return ResourceManager.GetString("ReceiptNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipts View.
        /// </summary>
        public static string ReceiptsViewTextBlock {
            get {
                return ResourceManager.GetString("ReceiptsViewTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string RemoveButton {
            get {
                return ResourceManager.GetString("RemoveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of the required fields are blank.
        /// </summary>
        public static string RequiredFieldsMissing {
            get {
                return ResourceManager.GetString("RequiredFieldsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchFieldButton {
            get {
                return ResourceManager.GetString("SearchFieldButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit search.
        /// </summary>
        public static string SearchQuitButton {
            get {
                return ResourceManager.GetString("SearchQuitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to select an article first before adding it.
        /// </summary>
        public static string SelectArticleFirstError {
            get {
                return ResourceManager.GetString("SelectArticleFirstError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Sellers.
        /// </summary>
        public static string SellerMenuItem {
            get {
                return ResourceManager.GetString("SellerMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seller Name.
        /// </summary>
        public static string SellerNameHeader {
            get {
                return ResourceManager.GetString("SellerNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active account.
        /// </summary>
        public static string SellerViewIsActiveHeader {
            get {
                return ResourceManager.GetString("SellerViewIsActiveHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seller View.
        /// </summary>
        public static string SellerViewTextBlock {
            get {
                return ResourceManager.GetString("SellerViewTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string SellerViewUsernameHeader {
            get {
                return ResourceManager.GetString("SellerViewUsernameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Serbian.
        /// </summary>
        public static string SerbianLanguageMenuItem {
            get {
                return ResourceManager.GetString("SerbianLanguageMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Settings.
        /// </summary>
        public static string SettingsMenuItem {
            get {
                return ResourceManager.GetString("SettingsMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PC Component Store.
        /// </summary>
        public static string StartingWindow {
            get {
                return ResourceManager.GetString("StartingWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products View.
        /// </summary>
        public static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Themes.
        /// </summary>
        public static string ThemeMenuItem {
            get {
                return ResourceManager.GetString("ThemeMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Price.
        /// </summary>
        public static string TotalPriceHeader {
            get {
                return ResourceManager.GetString("TotalPriceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string TotalTextBlock {
            get {
                return ResourceManager.GetString("TotalTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string UpdateButton {
            get {
                return ResourceManager.GetString("UpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username field cannot be blank.
        /// </summary>
        public static string UsernameEmptyErrorMessage {
            get {
                return ResourceManager.GetString("UsernameEmptyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username*.
        /// </summary>
        public static string UsernameTextBlock {
            get {
                return ResourceManager.GetString("UsernameTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string ViewButton {
            get {
                return ResourceManager.GetString("ViewButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _View.
        /// </summary>
        public static string ViewMenuItem {
            get {
                return ResourceManager.GetString("ViewMenuItem", resourceCulture);
            }
        }
    }
}
